version: "3.1"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: shopee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    # this option mounts the local folder ./pg-data to the container folder /var/lib/postgresql/data
    # which makes the data persistent even if the container is deleted
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
